// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_storee.Models;

#nullable disable

namespace dotnet_storee.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("dotnet_storee.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategori");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategoriAdi = "Telefon",
                            Url = "telefon"
                        },
                        new
                        {
                            Id = 2,
                            KategoriAdi = "Giyim",
                            Url = "giyim"
                        },
                        new
                        {
                            Id = 3,
                            KategoriAdi = "Beyaz Eşya",
                            Url = "beyaz-esya"
                        },
                        new
                        {
                            Id = 4,
                            KategoriAdi = "Kozmetik",
                            Url = "kozmetik"
                        },
                        new
                        {
                            Id = 5,
                            KategoriAdi = "Elektronik",
                            Url = "elektronik"
                        },
                        new
                        {
                            Id = 6,
                            KategoriAdi = "Elektronik",
                            Url = "elektronik"
                        },
                        new
                        {
                            Id = 7,
                            KategoriAdi = "Elektronik",
                            Url = "elektronik"
                        },
                        new
                        {
                            Id = 8,
                            KategoriAdi = "Elektronik",
                            Url = "elektronik"
                        },
                        new
                        {
                            Id = 9,
                            KategoriAdi = "Elektronik",
                            Url = "elektronik"
                        },
                        new
                        {
                            Id = 10,
                            KategoriAdi = "Elektronik",
                            Url = "elektronik"
                        });
                });

            modelBuilder.Entity("dotnet_storee.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Slider");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Slider 1 Açıklama",
                            Aktif = true,
                            Baslik = "Slider 1 Başlık",
                            Index = 0,
                            Resim = "slider-1.jpeg"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Slider 2 Açıklama",
                            Aktif = true,
                            Baslik = "Slider 2 Başlık",
                            Index = 1,
                            Resim = "slider-2.jpeg"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Slider 3 Açıklama",
                            Aktif = true,
                            Baslik = "Slider 3 Başlık",
                            Index = 2,
                            Resim = "slider-3.jpeg"
                        });
                });

            modelBuilder.Entity("dotnet_storee.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktif")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Anasayfa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resim")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunAdi")
                        .HasColumnType("TEXT");

                    b.Property<double?>("fiyat")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Senemsssssss",
                            Aktif = false,
                            Anasayfa = true,
                            KategoriId = 1,
                            Resim = "1.jpeg",
                            UrunAdi = "Apple Watch 8",
                            fiyat = 10000.0
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Senemsssssss",
                            Aktif = true,
                            Anasayfa = true,
                            KategoriId = 1,
                            Resim = "2.jpeg",
                            UrunAdi = "Apple Watch 9",
                            fiyat = 20000.0
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Senemsssssss",
                            Aktif = true,
                            Anasayfa = true,
                            KategoriId = 2,
                            Resim = "3.jpeg",
                            UrunAdi = "Apple Watch 10",
                            fiyat = 30000.0
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Senemsssssss",
                            Aktif = false,
                            Anasayfa = true,
                            KategoriId = 2,
                            Resim = "4.jpeg",
                            UrunAdi = "Apple Watch 11",
                            fiyat = 40000.0
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Senemsssssss",
                            Aktif = true,
                            Anasayfa = true,
                            KategoriId = 2,
                            Resim = "5.jpeg",
                            UrunAdi = "Apple Watch 12",
                            fiyat = 50000.0
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Senemsssssss",
                            Aktif = true,
                            Anasayfa = false,
                            KategoriId = 3,
                            Resim = "6.jpeg",
                            UrunAdi = "Apple Watch 13",
                            fiyat = 60000.0
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Senemsssssss",
                            Aktif = true,
                            Anasayfa = false,
                            KategoriId = 3,
                            Resim = "7.jpeg",
                            UrunAdi = "Apple Watch 14",
                            fiyat = 70000.0
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Senemsssssss",
                            Aktif = true,
                            Anasayfa = true,
                            KategoriId = 4,
                            Resim = "8.jpeg",
                            UrunAdi = "Apple Watch 15",
                            fiyat = 80000.0
                        });
                });

            modelBuilder.Entity("dotnet_storee.Models.Urun", b =>
                {
                    b.HasOne("dotnet_storee.Models.Kategori", "Kategori")
                        .WithMany("Uruns")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("dotnet_storee.Models.Kategori", b =>
                {
                    b.Navigation("Uruns");
                });
#pragma warning restore 612, 618
        }
    }
}
